name: Build ForceCloseOreUI

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        target: 
          - arm64-v8a
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r26b # Recommended NDK version for stable Dobby builds
        
    - name: Setup Xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
        
    - name: Configure and Build
      run: |
        # The --yes flag tells Xmake to automatically download and build Dobby without pausing
        xmake f -p android --ndk=${{ steps.setup-ndk.outputs.ndk-path }} -a ${{ matrix.target }} -c --yes
        xmake
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ForceCloseOreUI-${{ matrix.target }}
        path: build/android/${{ matrix.target }}/release/libForceCloseOreUI.so
